### ISSUE TITLE
FAQ missing important financialisation information 

### ISSUE THREAD

**Issue by GalacticPrez** [OdyseeTeam/odysee-docs#431]
I looked through the FAQ on the website and for the life of me couldn't find a simple definitive page or section telling me exactly concisely clearly and unambiguously what Odysee takes from donations and sponsorships,  nor indeed a clear description of what all these possible options are - **and please don't point me to an existing page, as I already read through the entire relevant sections, so even if the information exists, my point still stands that it's not simple or easy to find or understand** - so you need to work on those explanations and the layout and organisation of the information, because it was not a good job done, and this is the most important thing for me when deciding to use this service or not ...

**HAVING SAID ALL THAT** ... I would nonetheless like to send my regards to the intentions of the business and many other good things you've done or intend to do, and in some respects, it is possible this could in the future fill a gap in my own vision relating to content development distribution and publication - and happy to talk privately on that matter in an audiovisual call if anyone on the project management team wants to talk about it - but for now, I'd just appreciate knowing more precisely and clearly what exactly the deal is ... I thought I saw the mention of Stripe there somewhere, and I know from memory that stripe will take something like 30 cents plus 2.75% of the sale, but I don't remember even seeing those details mentioned in your documentation, nor did I see anything about what odysee takes, nor even really a firm commitment in real numbers as to what is being offered per view, just some vague and unclear overview that really didn't give me any idea at all what it amounts to in real money ... so the point is, why would I bother with the effort if I don't know whether those efforts will just be wasted and I'll regret having wasted time on something that wasn't worth the investment of time and other resources ... IN OTHER WORDS AGAIN: you need to think about your site from MY view (the user) NOT from your own view, because I don't care about what you're getting out of it EXCEPT in so far as it may affect what I get out of it ... you follow?

**Comment by tzarebczan** [comment]
Did you come across this page? https://help.odysee.tv/payments-chart/

Should have everything there, let us know if something is missing.

**Comment by GalacticPrez** [comment]
> Did you come across this page? https://help.odysee.tv/payments-chart/
> 
> Should have everything there, let us know if something is missing.

Here's your layout problem then: as a new person goes down the list on the LHS in the menu (see screen capture below):
![5174F754-CD7D-45E6-BDCF-A238791CDF96](https://github.com/OdyseeTeam/odysee-docs/assets/17514819/9e0ae0a6-217a-4232-89c4-3396f7daeee2)
... as you can see, I first come across a section entitled "Monetisation & Rewards" - and opening that up, I should REASONABLY expect to find ALL information on that topic within that section, and having opened that section one cannot see the link you mention at the very bottom of the menu, and why would I think I need to look there anyway when I am already in the section in which I reasonably expect to find ALL information on the topic because that's the title you gave it ... so I think you really need to put that page into that section OR AT THE VERY LEAST put repeated hyperlinks to it, but I didn't see a single one, and the only way I would find it is if I concluded that this section which I reasonably expect to contain the information actually doesn't, but why would I conclude that, when the title tells me that it should?

do you see what I'm saying? It doesn't make any sense and on a tiny phone screen, the bottom of that menu isn't in view, and I have no reason to look for it in any section other than the one I'm in

**Comment by GalacticPrez** [comment]
The other part of my comment you also didn't reply to, being a better worded and organised description of the ways in which supporters can support you ... I found the wording very vague, and there's no mention of any ability to or differences between the notions of one off donation versus regular ongoing sponsorship - which may very well be a feature of stripe itself and you may think to yourself "this is not our job to describe it to the user", but such an attitude is short sighted, because you're going to get a lot of people who are new to podcasting and not familiar with all the options, like myself, where I've been researching for a while, but I'm still undecided as to how best to achieve what I want to achieve and the way I want to do it (which isn't served entirely by any platform in existence and hence my need to long term develop a greater vision to make it possible), but I do not have understanding of everything that can be done on every platform, and I really need documentation to be of better quality to help me make my decision
