### ISSUE TITLE
Upload blocked why ?

### ISSUE THREAD

**Issue by Razatator** [OdyseeTeam/odysee-docs#455]
I try to upload a video. Can you tell me what is blocking the upload, it's annoying to find yourself blocked without knowing why.
Usually it's because of a special character in the URL bar but here I don't understand why.
It would be simpler to have an explanatory error message so as not to get stuck.

**Comment by tzarebczan** [comment]
Please email us at help@odysee.com with details of your issue if you're still having it.

**Comment by Razatator** [comment]
Hi the details, it's a bug I encouter with the upload box. I clear the app dowload and retry the same way and it's working. But if you insert in your code an Error message when you don't fill out the fields correctly to upload, this would help a lot. Rather than being stuck with no way out, pressing an upload button that doesn't want to execute. The reason is often, as I wrote previously, to have used a special character or a space in the U.R.L or title creation bar, but you have to understand it for yourself without an explanatory error message. Just fix it for a better user experience.
