### ISSUE TITLE
ask a question.

### ISSUE THREAD

**Issue by mastergithub3574** [OdyseeTeam/odysee-docs#497]
if i fictionally synced my youtube channel (saying fictionally,we're also calling this channel 'player2'), to my odysee channel (lets call it 'player1'), will it delete my odysee channel?

**Comment by zimm3rmann** [comment]
Please contact us at help@odysee.com, we don’t provide support via GitHub issues. 

Thanks!

**Comment by mastergithub3574** [comment]
i cant email you...my email doesnt like emailing to foreign email providers...
